### ISSUE TITLE
Circle around the buttons

### ISSUE THREAD

**Issue by brunodeandrade** [Kadasiddha/dailPad#1]
Hello, I included your code in mine, but the circles around the buttons has disappeared. 
Any clues why? 

Thank you.

**Comment by Kadasiddha** [comment]
Hi,
I have tested this code and its working fine on swift 3. I have update the swift 3 changes on Github. Try downloading the code now.

Regards,
Sid

**Comment by Kadasiddha** [comment]
Hi,
Also check 'Images.xcassets' consist of image called 'normal'. Add it to your project if its not present and go to 'Main.storyboard' of your project. Select all the buttons and then go to 'Show the attributes inspector' and set the background image as 'normal'. Hope this will solve your issue. :)

**Comment by brunodeandrade** [comment]
I checked my project, and I the 'Images.xcassets' was not there. After the addition, everything went normal! 
Thank you! :)
